### ISSUE TITLE
[Ubuntu 20.04 LTS] Graphic bug?

### ISSUE THREAD

**Issue by simbleau** [hasenbanck/egui_example#6]
Haven't performed any diagnostics, but this is what I see after building a fresh repo clone.

It is interactive and I can move the Widget Gallery, but none of the items except for the plot display correctly.

![image](https://user-images.githubusercontent.com/48108917/118399684-4ce7ad80-b62c-11eb-9284-04dbe615c5f9.png)

**Comment by hasenbanck** [comment]
Most likely an issue with the old Cargo.lock.  I removed it.
Update and run "cargo update && cargo run"

**Comment by simbleau** [comment]
That worked! perfect!.
